- REQUIRE
- src/GeoInterface.jl
- src/geotypes.jl
I can't seem to get the `Union{..}` stuff to work
```julia
| | |_| | | | (_| |  |  Version 0.3.11 (2015-07-27 06:18 UTC)
_/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0
julia> using Compat
julia> @compat(Union{Int,Float64})
ERROR: type: instantiate_type: expected TypeConstructor, got Function
```
> WIP: fix deprecation warnings

- .travis.yml
- README.md
- REQUIRE
- src/geotypes.jl
- test/runtests.jl
I think after merging this I'll tag a new version. The current release is quite old and uses `Nothing`, which was deprecated in v0.4, and is gone in v0.5.
Are there any other things that should still be done before tagging a new version?
> drop julia 0.3 support

- REQUIRE
- src/GeoInterface.jl
- src/plotrecipes.jl
@visr @mkborregaard
Based on the discussion in https://github.com/JuliaGeo/Shapefile.jl/issues/12
So the example in the README of PlotRecipes.jl will now be:
```julia
using Plots, Shapefile
dir = "https://github.com/nvkelso/natural-earth-vector/raw/master/110m_physical/"
fn = "ne_110m_land.shp"
run(`wget $dir/$fn -P /tmp/`)
shp = open("/tmp/$fn") do fd
read(fd, Shapefile.Handle)
end
plt = plot()
for s in shp.shapes; plot!(plt, s); end
plt
```
and yield
Suggestions/improvements welcome!
> Add support for integration into Plots ecosystem

- src/plotrecipes.jl
they were wrong (and unused anyway; since only the recipe for
`geom::Vector{<:AbstractGeometry}` is used)
Martijn, can you help me verify on
```julia
;cd ~/.julia/v0.6/Shapefile/test
using Shapefile, Plots
f(i) = plot(open("shapelib_testcases/test$i.shp") do f
read(f, Shapefile.Handle).shapes
end, alpha=0.5)
plot([f(i) for i in 1:12]...)
```
It should give
> Remove unused `shapecoords()` methods

- src/GeoInterface.jl
- src/operations.jl
- test/runtests.jl
Fixes #21.
Only implementing the uncontroversial part now, for `Point`s.
> Add comparison operators for some geometry types.

- src/plotrecipes.jl
FWIW, in Julia v0.7 `warn` was deprecated, changed to `@warn`.
> use warn macro

- src/plotrecipes.jl
Fixes this case
```julia
using Plots, Shapefile
shp = Shapefile.shapes(Shapefile.Table("IndoPacific_Islands1332.shp"))
plot(shp)
```
Which otherwise failed
> Fix plotting for shapefiles with multiple polygons

- src/plotrecipes.jl
I think there are several use cases where one wants to specify an other aspect ratio than 1, e.g. when plotting geometries in spherical coordinates.
> allow setting of aspect_ratio

- src/plotrecipes.jl
This PR addresses the following issue:
Assume the following code example:
```julia
using GeoInterface, Plots
plot(1:3,1:3, aspect_ratio=2, legend=true)
ls = LineString([[0.,0.],[1.,0.],[1.,1.],[0.,1.], [0.,0.]])
plot!(ls)
```
The mutating call `plot!(ls)` resets the previous set `aspect_ratio` and `legend` arguments to the value defined in the recipe of this package.
This PR changes the above described behavior in the following way:
for `aspect_ratio`:
only set the `aspect_ratio` for the first plot series and not for mutating calls of `plot!()`
for `legend`:
replace `legend --> false` with `label --> :none`
this ensures that there will be no `legend` as long as you only add subtypes of  `AbstractGeometries` without an explicit `label`
> only set aspect_ratio on nonmutating calls of plot()

- src/defaults.jl
- src/interface.jl
This PR adds `getpolygons` and `getrings` functions to allow efficient access to all poylgons and rings in cases like Shapefile.jl where exterior and holes are not clearly separated in the spec. Packages like Rasters.jl don't actually care if they are separated so loading them all directly is much more efficient. 
The fallback is to iterate over all polygons and rings.
> add getpolygons and getrings functions

- src/defaults.jl
I noticed we sometime pass the trait on to called methods, sometimes not. And we use varying names for the trait argument. This just standardises everything so the trait is always forwarded to the next method, and is always called `t`. Also caught a few argument bugs where the trait was passed instead of `geom`.
> standardise trait arg passing

- docs/src/guides/developer.md
- docs/src/tutorials/usage.md
- src/GeoInterface.jl
- src/fallbacks.jl
- src/interface.jl
- test/test_primitives.jl
This is onto the branch of #49, but separate because it might warrant some discussion.
One of the advantages of adding *Trait to all trait types, is that they wont clash with other packages. The disadvantage is that some of them get even longer, e.g. `GeoInterface.AbstractGeometryCollectionTrait`. But we can alleviate this by exporting all the traits. What do you think?
For my own reference, replacements made with
```
GeoInterface.(\w+)Trait
$1Trait
```
> export the traits

- .github/workflows/recipes.yml
- GeoInterfaceRecipes/Project.toml
- GeoInterfaceRecipes/README.md
- GeoInterfaceRecipes/src/GeoInterfaceRecipes.jl
- GeoInterfaceRecipes/test/runtests.jl
This PR adds plot recipes back to the interface, but using the traits. Its actually a lot simpler with traits.
To work automatically on e.g. Shapefile.jl and ArchGDAL.jl objects, we still need them to inherit from something we can dispatch on here. So I've added back the `AbstractGeometry` type as an entry point to things like this where packages want that. 
Packages that don't inherit from this can still use these plot recipes, but will need to add a RecipesBase dependency, and methods like this:
```julia
using RecipesBase
@recipe f(geom::AbstractPackageGeom) = GeoInterface.geomtype(geom), geom
@recipe @recipe function f(geom::Vector{<:Union{Missing,AbstractGeometry}})
for g in skipmissing(geom)
@series begin
GeoInterface.geomtype(g), g
end
end
end
```
Edit: an alternative to merging …
> add trait based plot recipes in a subpackage

- src/fallbacks.jl
When implementing the GeoInterfaceRecipes for ArchGDAL, I found that `is3d` is not defined for types other than Points.
> Extend usage of is3d and ismeasured to all traits.

- src/base.jl
- src/interface.jl
- src/types.jl
- test/test_primitives.jl
This changes a few things from the last PR #61 
Features are now defined for any `NamedTuple` that has a `geometry` field, and all other fields are `properties`.
An `AbstractTrait` type is also added to unify all the traits.
Some of these methods like `geometry` and `nfeature` are returning `nothing` where they could instead throw a `MethodError` like another object without the method defined. I'm not sure which is best here.
> Features fixes

- src/base.jl
- test/test_primitives.jl
This fixes `Tuple` and `NamedTuple` points for mixed integers and where `trait` was only looking at `NamedTuple` as a `FeatureTrait` rather than also as a `PointTrait`
See https://github.com/JuliaGeo/Leaflet.jl/issues/6
> fix dispatch on base types and test them

- docs/src/guides/developer.md
- src/fallbacks.jl
- src/interface.jl
- test/test_primitives.jl
Following discussion in #49.
I tried implementing Base.convert as suggested by the [GeoInterface docs](https://juliageo.org/GeoInterface.jl/stable/guides/developer/#Conversion) for GeometryBasics, testing with GeoJSON geometries.
The first method is needed to send the 2-arg convert through the 3-arg method with the trait argument.
```julia
function Base.convert(::Type{T}, geom) where {T<:AbstractGeometry}
return convert(T, GeoInterface.geomtrait(geom), geom)
end
```
This method is `geom::Any`, so if there are any convert methods with more specific types already defined, I cannot hit this anymore. This was the case with trying to `convert(GeometryBasics.Point, p::GeoJSON.Point)`. `GeoJSON.Point` is an `AbstractVector`, and there is a method defined for those already. However that method …
> stop using Base.convert

- src/fallbacks.jl
- test/test_primitives.jl
Somehow this didn't make it in before
> use isdefined to check module has geointerface_geomtype function

- Project.toml
- src/fallbacks.jl
- src/interface.jl
- test/test_primitives.jl
While slow, it's very useful for packages that don't implement it itself, as we use `extent` in packages such as https://github.com/evetion/GeoAcceleratedArrays.jl/pull/3
> Added fallback method for `extent`.

- src/base.jl
- src/interface.jl
- test/test_primitives.jl
Some performance and correctness fixes. As much as possible we check that tuples and vectors are the right length.
I think the performance of GeoJSON was also affected by how slow the Vector methods were here - they are 100x faster now.
Found working on #78. Lets get this merged quickly so that can be merged
> fix performance and correctness of base points, and test

- GeoInterfaceRecipes/src/GeoInterfaceRecipes.jl
- GeoInterfaceRecipes/test/runtests.jl
Found linear ring had no recipe while working on https://github.com/JuliaGeo/Shapefile.jl/pull/85
I'm not sure how this worked before for `LinearRing`, it already had tests but were failing on 1.9 for me.
I also tested `LineString` while fixing this.
> add LinearRing recipes and test plotting, also test LineString

- docs/src/guides/developer.md
- src/fallbacks.jl
- src/interface.jl
- test/test_primitives.jl
@evetion what do you think of falling back to `Extents.extent` ?
It would solve e.g. this issue https://github.com/rafaqz/Extents.jl/issues/7
Also means packages can define `Extents.extent` instead of `GeoInterface.extent`. So the difference would be that `GeoInterface.extent` calculates the extent if it doesn't exist because it knows how to do that with geometries.
That may have solved my earlier issue with always doing the calculations, wish I thought about this more then...
> fall back to Extents.extent

- src/fallbacks.jl
Over at https://github.com/JuliaGeo/LibGEOS.jl/issues/160, this makes `@code_warntype` green for `coordinates(polygon)` and changes the type for coordinates on a MultiPolygon from Any to a Vector.
> Use map instead of collect with a broadcast.

- src/wrappers.jl
- test/test_wrappers.jl
Some packages don't have `LinearRing` types and builld `Polygon` from `LineString`, so that should be allowed here.
> allow LineStringTrait in Polygon wrapper

- GeoInterfaceMakie/src/GeoInterfaceMakie.jl
- GeoInterfaceRecipes/src/GeoInterfaceRecipes.jl
- GeoInterfaceRecipes/test/runtests.jl
This PR standardizes the `@enable` macro across GeoInterfaceRecipes and GeoInterfaceMakie (mostly to follow GeoInterfaceMakie, its cleaner). The `@enable_geo_plots` macro is kept for compat reasons.
It also applies both `@enable` macros to GeoInterface.Wrappers geometries - this seems to be the only place we can do that given the dependency structure.
> Standardise `@enable` and apply it to `WrapperGeometry`

- GeoInterfaceMakie/src/GeoInterfaceMakie.jl
- GeoInterfaceMakie/test/runtests.jl
@asinghvi17 I took the liberty of making a PR from your branch, I have this array code somewhere too but we may as well merge this instead. `Float64` is also better for high resolution things, going on the FLoat32 artifacts we see at high zooms in Tyler.jl....
~~A test of plotting the vectors could help I guess~~ done
> Use GI.convert for Makie plots, allow arrays

- src/GeoInterface.jl
- src/fallbacks.jl
- src/interface.jl
- test/test_primitives.jl
This PR lets non-geometries pass through to Extents.jl if used in `GeoInterface.extent`. Just a convenience really so the function here just works in more cases.
I also used `import` rather than `using` at the same time for correctness.
> Tweak extent fallback

- .github/workflows/CompatHelper.yml
This makes sure we run CompatHelper on all sub-packages, such that for instance Makie breaking releases (#113) are not forgotten.
```julia
import CompatHelper
CompatHelper.main(; subdirs=[
".",
"GeoInterfaceMakie",
"GeoInterfaceRecipes",
])
```
The diff is a bit larger since I update to the latest suggested workflow from https://github.com/JuliaRegistries/CompatHelper.jl.
Actually I don't think the old CompatHelper ever worked since I don't see it installing Julia or using Actions.
> Run CompatHelper on sub-packages as well

- src/fallbacks.jl
- test/test_primitives.jl
This PR loosens the type in the `crs` fallback so that `crs(x) == nothing` for non geointerface `x`.
It also tests this fallback for both `crs` and `extent`
edit:
```julia
julia> GeoInterface.crs(1)
ERROR: MethodError: no method matching crs(::Nothing, ::Int64)
```
> Add crs is nothing fallback for non-geointerface types

- GeoInterfaceMakie/Project.toml
- GeoInterfaceMakie/src/GeoInterfaceMakie.jl
- GeoInterfaceMakie/test/runtests.jl
Minor change to allow `missing` in GeoInterfaceMakie plots. 
This is needed for Shapefile.jl makie recipes.
> allow missing in arrays for Makie plots

- src/interface.jl
- test/test_primitives.jl
I was doing some data processing and having `|> GI.convert(LibGEOS) |> ...` would have been handy, so I coded this up.
> Add a 1-arg curried version of `GI.convert`

- GeoInterfaceMakie/Project.toml
- GeoInterfaceMakie/src/GeoInterfaceMakie.jl
- GeoInterfaceMakie/test/runtests.jl
This upstreams GeoMakie.to_multipoly and its variants into GeoInterfaceMakie.  Performance needs improvement but this is otherwise ready for review, and I have tested it works.
Usecase:
```julia
using NaturalEarth
using CairoMakie
fc = NaturalEarth.naturalearth("admin_0_countries", 10)
plot(fc.geometry)
```
without any fuss or muss.
> Allow vectors with mixed single and multi geometries to be plotted in Makie

- Project.toml
The 1-arg convert PR is still unreleased, wanted to release that.
> Bump GeoInterface patch version

- GeoInterfaceMakie/Project.toml
- GeoInterfaceMakie/src/GeoInterfaceMakie.jl
- GeoInterfaceMakie/test/runtests.jl
This PR replaces missings with NaN geometries (not quite empty, but close).  The infrastructure to change types is all there but it needs some way to get the coordinate type from a geometry - this may be better implemented via the proposed `GI.coordtype` method.
Fixes #138
> Handle vectors with missings correctly in GeoInterfaceMakie

- src/fallbacks.jl
- src/interface.jl
- src/types.jl
To distinguish between *geographic* and *projected* coordinate systems. Fixes #119.
> Implement `crstrait`.

- src/wrappers.jl
When creating a geometry from an array that contains elements with the wrong trait, refer to the first element that has the wrong trait, rather than the first element of the array.
MWE:
```julia
import GeoInterface as GI
p = GI.Point(0,0)
x = 1
GI.Line([p, x])
```
Before this PR throws a
```
ERROR: ArgumentError: GeoInterface.LineTrait must have child objects with trait GeoInterface.PointTrait, got GeoInterface.Wrappers.Point{false, false, Tuple{Int64, Int64}, Nothing} with trait 
GeoInterface.PointTrait()
```
After this PR throws a: 
```
ERROR: ArgumentError: LineTrait must have child objects with trait PointTrait, got Int64 with trait nothing
```
> Better child error when creating geom from array

- src/utils.jl
- src/wrappers.jl
Fixes https://github.com/evetion/WellKnownGeometry.jl/issues/37.
Packages should implement the two argument interface methods for geometries, and #124 did not. In WKG I assumed I could call `ncoord(trait, geom)`, which failed.
> Correctly implement interface for wrapper geometry.

- src/wrappers.jl
- test/test_wrappers.jl
Proposing a fix for [this issue](https://github.com/JuliaGeo/GeoInterface.jl/issues/126) where we modify the displayed text for our wrapper geometries. Each geometry can be displayed in "regular" or "compact" form which will influence how much information is shown to the user. This should make things a bit clearer so we don't get spammed with the raw fields that can be hard to follow.
> Fix printing wrapper geoms

- Project.toml
- docs/src/guides/developer.md
- src/GeoInterface.jl
- src/fallbacks.jl
- src/interface.jl
- src/metadata.jl
- test/test_dataapi.jl
> Implement crs and geometrycolumn fallbacks via DataAPI

- src/wrappers.jl
- test/test_wrappers.jl
Supersedes #177 
Fix #176 #182
- forward 2-arg show(io, geom) to 3-arg show(io, MIME"text/plain"(), geom)
- Wrap CRS in quotes when showing, so that geometries can be copy/pasted at least
- bugfix missing or wrongly named variables / typos when showing wrapper geometries
- bugfix show
- fix point show by adding a screen_ncols kwarg
- use sprint() instead of global IOBuffers in testing, so that it can be made interactive
- force display size to be consistent in the test function
- Test the printing of wrapped (rapped ;)) geometries
> More show improvements

- Project.toml
- src/utils.jl
- test/test_primitives.jl
The interface actually tells you to do so, but it's easy to forget/skip. Found this for `isgeometry(GFT.WellKnownBinary)` (blessed piracy in [WellKnownGeometry](https://github.com/evetion/WellKnownGeometry.jl/pull/41)) when working on [GeoArrow](https://github.com/JuliaGeo/GeoArrow.jl/pull/2) purely based on the types of a column (not the first instance or similar).
> Test isgeometry on type of geometry.

- src/fallbacks.jl
- src/interface.jl
This allows the trait to be passed through completely from the time of discovery to the bottom level, which decreases allocations and dynamic dispatch in long call chains like GeometryOps' `apply`.
If this makes sense to add then I will add tests, docs, etc.
> Add a convert method for (module, trait, geom)
